### ISSUE TITLE
Front end (Main page)

### ISSUE THREAD

**Issue by devpato** [jmhaineault/Boogle#4]
The following still need to be implemented:

- [x] Show a map with all the returned
businesses. Each marker should have a pop-up info window that has its corresponding
business name and the full address
- [x] For each returned business, provide a way for users to access its Google street view
- [x] For each returned business, provide a way to direct user to the Twitter search page
- [x] For each returned business, provide a way for users to access all the reviews

**Comment by justinkusz** [comment]
Cool. This being my first time using github issues, should we open a new issue for each "feature" of the main page? For example, an issue for some jQuery to perform a business search and display the results.

**Comment by devpato** [comment]
we can do one issue per feature or we do checklists @justinkusz 
Example:
Main page issue
- [ ] jQuery
- [ ] Table
- [ ] Logo

**Comment by justinkusz** [comment]
The following still need to be implemented:

- [ ] Show a map with all the returned
businesses. Each marker should have a pop-up info window that has its corresponding
business name and the full address
- [ ] For each returned business, provide a way for users to access its Google street view
- [ ] For each returned business, provide a way to direct user to the Twitter search page
- [ ] For each returned business, provide a way for users to access all the reviews
